version: 2

sources:
  - name: raw
    database: DBT_DEV
    schema: RAW
    tables:
      - name: clients
      - name: commandes
      - name: commandes_europe
      - name: commandes_usa
      - name: logs_connexion
      - name: logs_connexion_v2